remote_theme: kosatyi/sjt

navigation: false
projects: true

baseurl: /fondy-checkout

brand: fondy-checkout
title: Fondy Checkout Widget
description:

author:
  name: Stepan Kosatyi
  url: https://kosatyi.com/