plugins:
  - jekyll-seo-tag

port: 4001

styles:

remote_theme: kosatyi/sjt

exclude:
  - vendor
  - src

javascript:

baseurl: /node-gettext-generator

navigation: false

projects: true

brand: fondy-checkout
title: Fondy Checkout Widget
description:
analytics: UA-37629144-1

author:
  name: Stepan Kosatyi
  url: http://www.kosatyi.com/

toolbar:
